### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by radekmie** [onury/docma#1]
Any CLI planned?

**Comment by onury** [comment]
Yes, as soon as I make time. 

This will take config file path as an argument (since there are too many options) and maybe a few most important ones.

**Comment by radekmie** [comment]
This would be enough in most cases.

**Comment by sprusr** [comment]
@onury had a crack at it, please let me know what you think. Happy to work on changes based on suggestions, or for you to do so.

**Comment by onury** [comment]
Thanks for taking the time but this is implemented in v1.2.0 (just released).
See [CLI reference here](http://onury.github.io/docma/?content=docma-cli).

BTW, I wouldn't use optimist package. It's not maintained anymore. 
Docma uses [yargs](https://github.com/yargs/yargs) package for CLI.
