### ISSUE TITLE
Support ES7 Async/Await

### ISSUE THREAD

**Issue by macdja38** [onury/docma#11]
node docma.js
    Error: ERROR: Unable to parse C:\Users\macdja38\WebstormProjects\pvpcraft\lib\MessageSender.js:  Unexpected token _getWebhook

        at ChildProcess.<anonymous> (C:\Users\macdja38\WebstormProjects\pvpcraft\node_modules\jsdoc-x\src\lib\helper.js:143:35)
        at emitTwo (events.js:106:13)
        at ChildProcess.emit (events.js:192:7)
        at maybeClose (internal/child_process.js:890:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Where `_getWebhook` is declaired as

    async _getWebhook(channel)

**Comment by withinboredom** [comment]
also arrow functions:

```
ERROR: Unable to parse /home/robert/code/soaring-octopus/lib/Actor.js: Unexpected token =>
```

**Comment by onury** [comment]
Docma uses JSDoc for parsing. See this [JSDoc issue](https://github.com/jsdoc3/jsdoc/issues/1188). I'll update as soon as it's officially supported.

**Comment by macdja38** [comment]
@onury any chance you could integrate this plugin in the time being, or if it's possible for us to do so let us know how, I took a look through the docs but I couldn't find anything on providing jsdoc plugins https://www.npmjs.com/package/jsdoc-strip-async-await

**Comment by onury** [comment]
@macdja38 Docma depends on [`jsdoc-x`](https://github.com/onury/jsdoc-x) (I'm the author) which uses official [jsdoc](https://github.com/jsdoc3/jsdoc) internally. I'll see if I can add a `plugins` option to jsdoc-x so it's reflected in Docma build configuration.  I'll look into it.

**Comment by onury** [comment]
Released Docma v.1.4.5
Pls see [build configuration](http://onury.github.io/docma/?api=docma#Docma~BuildConfiguration) for new JSDoc options such as `jsdoc.plugins`.

**Comment by onury** [comment]
@macdja38 jsdoc plugin support is a good workaround for this.  Tested..
Since this is not a Docma issue, closing.

Note: Also check out [v1.5.0 changes](https://github.com/onury/docma/blob/master/CHANGELOG.md#v150-release-2017-03-10) for other improvements..

**Comment by macdja38** [comment]
Thank you very much for the fix, it's been working well!
