### ISSUE TITLE
Using README as title page?

### ISSUE THREAD

**Issue by vernak2539** [onury/docma#12]
Is there a way to use the readme as the initial page? Maybe I'm just missing it in the docs... 

this is what I have, which executes jsdoc well, but doesn't have the title page (like your docs :))

```js
    return Docma.create()
      .build({
        src: [
          './index.js',
          './README.md'
        ],
        dest: './docs'
      });
```

**Comment by onury** [comment]
Sure. You just need to set app entrance.
```js
{
    src: [
      './index.js',
      './README.md'
    ],
    dest: './docs',
    app: {
         entrance: 'content:readme'
    }
}
```
See [build confoguration docs](http://onury.github.io/docma/?api=docma#Docma~BuildConfiguration) and this repo's own [docma.config.json](https://github.com/onury/docma/blob/master/docma.config.json) for an example.

Closing this. Pls re-open if you need to.

**Comment by vernak2539** [comment]
cheers! thanks for the quick response
