### ISSUE TITLE
Support @example <caption> style of jsdoc

### ISSUE THREAD

**Issue by kid-wumeng** [onury/docma#14]
Hi, I 'm a docma template user and it's amazing beautiful, but i see the docma do not support the `<caption>` style of @example, the api-doc is:

http://usejsdoc.org/tags-example.html

**Comment by onury** [comment]
Hi. Docma supports `@example` tag. Why do you think it doesn't? Pls provide your configuration and sample code/documentation.

**Comment by onury** [comment]
This is supported in Docma v2.0.0.
Thanks.
