### ISSUE TITLE
Static definitions inside a ES2015 class cause errors

### ISSUE THREAD

**Issue by offtherailz** [onury/docma#18]
This : 
```
class FullScreenButton extends React.Component {
    static propTypes = {
```
Causes an error like: 
```
ERROR: Unable to parse /......./FullScreenButton.jsx: Unexpected token =
```

Also this fails:
```
getButtonProperties = () => {
// ...
}
```

**Comment by onury** [comment]
Docma currently supports JSDoc v3.4.3 ([latest stable version](https://github.com/jsdoc3/jsdoc/blob/master/CHANGES.md) as of Jun, 2017). 

[Static methods](http://usejsdoc.org/howto-es2015-classes.html) (and getters/setters) [would work](http://www.ecma-international.org/ecma-262/6.0/#sec-class-definitions) but static (property) fields seem a stage-1 proposal which is [currently not supported](https://github.com/jsdoc3/jsdoc/issues/555#issuecomment-155217897) by JSDoc yet.

Once JSDoc supports it, Docma will.

**Comment by offtherailz** [comment]
Thank you,
I supposed it was a jsdoc issue. Even if not supported I hope there is a solution to avoid documentation generation to crash, because it is the automatic conversion suggested by facebook to migrate to react 15 that uses that syntax to autobind functions. 
We would try to find a solutions to propose to acorn / acorn-jsx (the JS parser at the end of the chain) they can accept.

**Comment by onury** [comment]
That crash/issue (with your static property example) is [fixed](https://github.com/jsdoc3/jsdoc/issues/1419#issuecomment-319853169) by JSDoc v3.5.4 which is the version Docma will run with the new release.

This will also add support for arrow methods and code with most [ES2015 features](https://github.com/jsdoc3/jsdoc/issues/555#event-1175059313).

I still have some work with the new release; but won't take too long though.

**Comment by jayesbe** [comment]
@onury  any idea when a new version will be released.. I thought it would be as easy as just updating the jsdoc-x dependency but its still failing for me on arrow functions

    const example = () => { } 

causes an error on page load which results in a no render

`Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at app.min.js:1
    at Array.reduce (<anonymous>)
    at app.min.js:1
    at Object.dust.filter (docma-web.js:4)
    at Chunk.reference (docma-web.js:4)
    at body_0 (docma-web.js:27)
    at load (docma-web.js:4)
    at Chunk.partial (docma-web.js:4)
    at body_33 (docma-web.js:27)
    at Chunk.section (docma-web.js:4)`

**Comment by onury** [comment]
There are other things to be updated such as `jsdom` which itself also has breaking changes. I'm working on v2 (actually these are implemented already), just needs some more time for template adjustments, etc..

**Comment by onury** [comment]
Supported in Docma v2.0.0.
