### ISSUE TITLE
Add class inheritance diagrams

### ISSUE THREAD

**Issue by cpetry** [onury/docma#19]
Hi there,

I suggest adding a class (ECMAScript 2015) inheritance diagram for each class (similar like doxygen or other libs).
This could be quite fancy!

**Comment by cpetry** [comment]
Found an existing jsdoc inheritance builder at https://github.com/valerii-zinchenko/inheritance-diagram
Is it possible to integrate this?

**Comment by onury** [comment]
This is rather a Docma **template** feature. It could be done via a new template or could be added as a feature to the default template. I'll think about this. In the meantime, PRs are welcome.
