### ISSUE TITLE
@enum doesn't produce the possible values in the generate docs

### ISSUE THREAD

**Issue by dietergeerts** [onury/docma#20]
I can't seem to figure out how to have the actual possible values in the generated docs. I tried addng `/** @member {string} */` to the values, but that also doesn't work. I use `@readonly @enum {string}` on the object.

**Comment by onury** [comment]
Below example generates proper docs for enum:
```js
/**
 * Status enumeration.
 *
 * @enum {String}
 * @readonly
 */
const Status = {
    /**
     * Indicates the device is ready.
     * @type {String}
     */
    READY: 'ready',
    /**
     * Indicates the device is idle.
     * @type {String}
     */
    IDLE: 'idle'
};
```

**Comment by dietergeerts** [comment]
Tried, but wait, AHA, now I see, If the description is being left out of the values, they don't show up. imho, in many cases, enum values document theirselves if the name is chosen right.

**Comment by onury** [comment]
Docma has a configuration `buildConfig.jsdoc.undescribed` that specifies whether to include symbols without a description; which defaults to `false`. Pls see [documentation](http://onury.github.io/docma/?api=docma).

**Comment by dietergeerts** [comment]
It's not working.
This is what I got:
`
{
  "src": [
    "./src/**/*.js",
    "./docs/**/*.md"
  ],
  "dest": "./dist-docs",
  "app": {
    "entrance": "content:main",
    "routing": {
      "method": "path"
    }
  },
  "jsdoc": {
    "undescribed": true,
    "excludePattern": ".(states|module|component|directive|filter|resolve|test|events|decorator|service|config|data|dto).js$"
  }
}
`
`
/**
 * All available application user roles.
 * @readonly
 * @enum {string}
 */
export const USER_ROLE = {
    ADMIN: 'ADMIN',
    POWER_USER: 'POWER_USER',
    USER: 'USER',
};
`
And it results in:
![image](https://user-images.githubusercontent.com/7393706/29349367-c0426208-8259-11e7-9ac6-fa1fe982120a.png)

**Comment by onury** [comment]
Pls try moving `export` to the end. JSDoc somehow does not document as expected when `export` is used on the same line. Try like below and let me know if it works for you.
```js
/**
 * All available application user roles.
 * @readonly
 * @enum {string}
 */
const USER_ROLE = {
    ADMIN: 'ADMIN',
    POWER_USER: 'POWER_USER',
    USER: 'USER',
};
export { USER_ROLE };
```
I'll check if this is fixed with latest version of JSDoc; if not I'll file an issue with them.

**Comment by onury** [comment]
Also, I noticed that you don't have any documentation for your properties. I suggest you add some description for these properties for better docs.

```js
/**
 * All available application user roles.
 * @readonly
 * @enum {string}
 */
const USER_ROLE = {
    /**
     *  [ADMIN description]
     *  @type {String}
     */
    ADMIN: 'ADMIN',
    /**
     *  [POWER_USER description]
     *  @type {String}
     */
    POWER_USER: 'POWER_USER',
    /**
     *  [USER description]
     *  @type {String}
     */
    USER: 'USER',
};
export { USER_ROLE };
```

If you don't want to do that; Docma [default build config](http://onury.github.io/docma/?api=docma#Docma~BuildConfiguration) has some settings for this. 

`buildConfig.jsdoc.undocumented` (default: `false`) — Specifies whether to include undocumented symbols.
`buildConfig.jsdoc. undescribed ` (default: `false`) — Specifies whether to include symbols without a description.

**Comment by onury** [comment]
Tried your initial example. You should set both `.jsdoc.undocumented` and `.jsdoc.undescribed` to `true` to get the members of your enumeration documented. It definitely works that way.
