### ISSUE TITLE
How to omit constructor?

### ISSUE THREAD

**Issue by dietergeerts** [onury/docma#21]
We are writing AngularJS services, which are classes, and therefore, we don't need to document the constructor, but whatever I do, I can't get then to be not included. @ignore doesn't work for them. Is there a way or setting that I can not include the constructor, but keep the class api doc?

**Comment by onury** [comment]
This is not related to Docma, but rather a JSDoc question. Please use StackOverflow or other QA sites for this. 

You can take a look at JSDoc documentation. There is a [`@hideconstructor`](http://usejsdoc.org/tags-hideconstructor.html) tag. You could also mark it `@private` if you're not documenting private symbols.

**Comment by onury** [comment]
`@hideconstructor` tag is supported in JSDoc 3.5.0 and later. Docma currently supports JSDoc v3.4.3. This will be available with new Docma release.

**Comment by dietergeerts** [comment]
Thx.

**Comment by onury** [comment]
Available with Docma v2.0.0 — just released.
Thanks.

**Comment by dietergeerts** [comment]
Thx. The new version is looking good. Sure to try it out, as I still haven't found a good doc builder for my projects (not one that I like the results from and that can work with the crazy FP stuff in it.)
