### ISSUE TITLE
Relative Links in Markdown

### ISSUE THREAD

**Issue by jayesbe** [onury/docma#22]
Hey guys, wanted to thank you for this great project. Still waiting for ES6 support but otherwise its working nicely. I have one issue though related to relative links inside the README.md

example

I have a README.md file in the project root that contains the following lines

    - [Login](doc/login.md)
    - [Logout](doc/logout.md)

When the doc is generated.. the console spits out the following

    content  login       /login           content/login.html
    content  logout      /logout          content/logout.html

However, the content index.html still contains the doc/login.md.. it doesn't link to the new generated html files. 

And because of the base path..  being different between between the actual code and the documentation path.. the relative path doesn't resolve.

Any insights?  

Should the Markdown files point to the generated files instead of Markdown files ?

**Comment by onury** [comment]
You'd typically link to the final URL in your markdown.
```
- [Login](https://your-docs.com/login)
- [Logout](https://your-docs.com/logout)
```
But I assume you want to provide your docs both within GitHub as regular markdown and as Docma generated SPA.

I'll consider this but it's a bit problematic. 
e.g. is `folder.com/login.md` a relative link or an actual URL?
And what if you really want to link to relative `.md`?

**Comment by onury** [comment]
There is no proper way of implementing this. 
I suggest you link to SPA routes as mentioned previously, not relative source paths (of `.md` files).
