### ISSUE TITLE
Description removes Windows-style newlines.

### ISSUE THREAD

**Issue by warpdesign** [onury/docma#28]
Let's say I have a description like this one:

```html
/**
 * line 1
 *
 * line 2
**/
class foo {
}
```

If I save the file with Windows line-endings (`CRLF`), the generated symbol.description will be:

> line1line2

Which will end up rendering this description html:

```html
<p>line1line2</p>
```

If I save the save file with Unix line-endings (`LF`), the symbol.description will be correct:

> line1
>
> line2

Which end up rendering this description html:

```html
<p>line1</p>
<p>line2</p>
```

**Comment by onury** [comment]
Can you clone/download the master and try if this resolves the issue? I'm not a PC.

**Comment by warpdesign** [comment]
You don't need a PC to reproduce the problem: just save one of your js files with Windows line-endings.

VSCode does this, or you could use this command line to convert from Unix to Windows:

> sed 's/$'"/`echo \\\r`/" input.txt > output.txt

(output.txt and input.txt must be different).

**Comment by warpdesign** [comment]
I tested your patch: and it fixes the problem.

**Comment by warpdesign** [comment]
@onury Do you need more information?

**Comment by onury** [comment]
nope. I was just busy. Sorry for the wait. Released.

**Comment by warpdesign** [comment]
No need to be sorry :) Thanks!
