### ISSUE TITLE
How to include assets to generated documentation?

### ISSUE THREAD

**Issue by warpdesign** [onury/docma#29]
I have some images in one of the .md I'm using in my Docma documentation:

```md
![test](img/foo.png)
```

That's get transformed as:

```html
<img src="img/foo.png" alt="test" />
```

But the `img/foo.png` is not copied to the output folder so when reading the documentation I don't see the image.

Is there a way to specify an assets directory that will be added to the generated documentation? Or should I do it by hand?

**Comment by onury** [comment]
Currently you need to provide an absolute URL for images and/or include the assets while you upload the generated docs.

But this feature should be added definitely.

**Comment by onury** [comment]
New option `assets` is added in Docma v2.0.0
Thanks
