### ISSUE TITLE
New template

### ISSUE THREAD

**Issue by warpdesign** [onury/docma#30]
Just to let you know the documentation for [AthenaJS](https://athenajs.github.io/athenajs-documentation/) is now using Docma with a new template (which is based on Docma's default template) and is available [here](https://github.com/AthenaJS/athenajs/tree/master/docma-template) :)

**Comment by onury** [comment]
Glad to hear that. Nice work !

**Comment by mojavelinux** [comment]
I really like the type definition links you added. Is there a reason you didn't link to types within the API too? (For example, linking from the MapEvent constructor to the Map type). That would really be a nice feature to have in docma.

**Comment by onury** [comment]
Closing this now. We can improve the template(s) more once we get v2 out.

**Comment by warpdesign** [comment]
@mojavelinux Yes, there is a reason. I wanted to do it for API types too but it's not that easy since links can be in different API pages sections.

For example, the `?api=map` section contains documentation for Map, MapEvent, Tile but there's no way for me to know that when the links are generated.

I could hardcode it quite easily but I wanted something could be reused by anyone so I decided to leave it as is for now.

**Comment by mojavelinux** [comment]
Thanks for the explanation. That helps me think about how I'm going to approach this problem. I think links between types is essential in an API, so I'm going to need to find a way to do it if I'm going to be able to use docma for my API docs. This really does seem like something docma should be able to track internally.

**Comment by warpdesign** [comment]
I guess it should be possible to do that by poking into documentation global var but I had some timing constraints cc @onury.

I'll have a look when I can find some free time.

**Comment by onury** [comment]
This should be a template feature, rather than docma builder core.
Each symbol is a bookmark on that route/page. You could link it via hash.
e.g. `?api=map#MapEvent`

Linking could be done via a custom [Docma/Dust Filter](https://onury.io/docma/?content=docma-filters). So (for the default template) in the [`symbol` partial](https://github.com/onury/docma/blob/v2/templates/default/partials/widgets/symbol.html#L9), you'd do something like this;
```html
<code class="symbol-type">{symbol|$type_linked}</code>
```
`$type_linked` would be a custom filter, used instead of `$type` filter.
```js
docma.addFilter('type_linked', function (symbol) {
    // ...
});
```
I'll play with this in [v2 branch](https://github.com/onury/docma/tree/v2), let you know.

**Comment by warpdesign** [comment]
That's already what I am doing, the only problem was getting the correct api to link to.

**Comment by onury** [comment]
Alright. We can add a utility method to get link for a symbol in docma web-core.

**Comment by warpdesign** [comment]
@mojavelinux It wasn't so hard after all: I added link to API objects in the documentation.

I also did the same thing for returned types and for extend types.
