### ISSUE TITLE
Allow preview from local file URL

### ISSUE THREAD

**Issue by mojavelinux** [onury/docma#31]
Currently, the SPA can't be previewed via a local file URL. It always shows a 404 page.

I did manage to hack docma-web.js to enable hashbang routing, which allowed me to view an API via:

file:///path/to/output/index.html#!/?api=group

However, none of the links worked and it was pretty fragile in general.

Would it be possible to support previewing via a local file URL? This is the ideal mode for development, IMO.

**Comment by onury** [comment]
I don't think file URI scheme would ever work properly, especially with `base` tag (set via build configuration `app.base`).

Why don't you run a simple server? It's very easy to do so. 
You'd just run it once and then reload the page each time you make a change; as you would do regardless of URI scheme anyway..

- either run a simple server via Python:
```
cd /path/to/docs
python -m SimpleHTTPServer 9000
```
- or you could use [`http-server`](https://github.com/indexzero/http-server) node module:
```
cd /path/to/docs
http-server -p 9000
```

_Note: Docma v2 will be able to run a local server for your convenience. e.g. via CLI command `docma serve`._

**Comment by mojavelinux** [comment]
> Why don't you run a simple server? It's very easy to do so.

Given that it's an extra step, it ends up being a huge pain to remember to do. Browsing file URLs is much more friendly to my contributors (one less thing to have to explain).

> via CLI command docma serve.

I could live with that. I takes care of the extra step problem.

> I don't think file URI scheme would ever work properly

Given that I was able to prove that the hashbang URLs work fine, I'm not sure what the problem is. It was just a matter of flipping a switch. But I realize I may not be thinking of all the scenarios.

**Comment by onury** [comment]
You can check out [v2 branch](https://github.com/onury/docma/tree/v2). CLI currently has this feature.
_Note that this is work in progress, not guaranteed to be stable until merged to master and released._

Feel free to re-open this if you need to.

**Comment by onury** [comment]
We now have `docma serve` command.

**Comment by mojavelinux** [comment]
Great news! I look forward to trying it out!
