### ISSUE TITLE
Suggestion: do not remove .git when building documentation

### ISSUE THREAD

**Issue by warpdesign** [onury/docma#34]
When building the documentation, docma will empty the directory specified with the `-d` option.

Right now, I am generating the documentation at the root of a git repository, so that when I want to update the documentation, I just have to commit/push the new files to my repository to update the website.

But since docma empties the whole directory, it also removes the `.git` directory so I can't commit/push anymore.

Suggestion: allow to keep hidden files/directories (ie: starting with a dot). Or maybe a new option could allow to specify a list of files/patterns to keep?

**Comment by onury** [comment]
I see your point. Will look into it.

**Comment by onury** [comment]
Docma v2.0.0 is released. Now, Docma will NOT empty the destination directory by default. CLI has a new `--clean` option if you want all contents to be removed before building into the dest. dir.
