### ISSUE TITLE
Package published on npm has broken command line

### ISSUE THREAD

**Issue by nvonbulow** [onury/docma#38]
When I try running the `docma` command, it immediately crashes with `Cannot find module '../lib/docma'`. Upon further investigation, this is because, in the published version, the file is named `../lib/Docma.js`. Since Unix systems are case-sensitive, the file is not found. This seems to be more of an issue with the way you packaged Docma than with the actual code itself. It looks like the file is named correctly in the repo at the tag you specified.

**Comment by onury** [comment]
This is fixed in v2.1.0 
Thanks
