### ISSUE TITLE
inheritdoc not respecting "smart linking"

### ISSUE THREAD

**Issue by aaronmallen** [onury/docma#51]
given

```javascript
// ./lib/a.js
/**
 * A base class
 * @memberof myModule
 */
class A {}
```

```javascript
// ./lib/b.js
import A from './a'
/**
 * A child class
 * @memberof myModule
 * @extends myModule~A
 * @inheritdoc
 */
class B extends A {}
```

```javascript
// index.js
/** 
 * A module that does stuff
 * @module myModule 
*/
import B from './lib/b'
export default {B}
```
both the inheritance of properties and the "Extends" link properly generate for `B` but when you do:

```javascript
// ./lib/b.js
import A from './a'
/**
 * A child class
 * @memberof myModule
 * @extends A
 * @inheritdoc
 */
class B extends A {}
```
the inheritance breaks (i.e. none of the class properties are carried over) however the "Extends" link still points to the proper base class.

**Comment by onury** [comment]
Seems to be a [JSDoc](https://github.com/jsdoc3/jsdoc) issue. (Docma uses JSDoc to parse documentation.) 
See [@inheritdoc related issues](https://github.com/jsdoc3/jsdoc/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%22%40inheritdoc%22) before you decide to open a new one there.

Feel free to re-open if needed.
