### ISSUE TITLE
Same configuration does not work both locally and in GitHub pages

### ISSUE THREAD

**Issue by adampbragg** [onury/docma#57]
I can navigate the SPA locally or in the remote GitHub pages. But, I cannot get the configuration right so I can navigate in both with the same configuration.

If I have the base set like so:
`"base":"/myrepo"` then the navigation works in GitHub pages but not locally.
If I have the base set like:
`"base":"/"` or `"base":""` then the navigation works locally but not in GitHub pages.

I think it is safe to assume that the paths of the SPA navigation are not relative to the directory from which the SPA originates and are instead based on the `<base>` tag.

I suggest that if no base configuration exists or it is set to an empty string that the generated paths be relative to the path from which the SPA originates.

If there is a way to configure the app so that a user can navigate the app both locally and in GitHub pages, I would love to hear about it.

**Comment by onury** [comment]
@adampbragg can you tell me:
- Your directory structure
- Where your docma.json exists
- From which directory you run the `serve` command
- Full command you use to start the server

**Comment by adampbragg** [comment]
Yes, give me 12 hours to get back to it.

**Comment by adampbragg** [comment]
@onury 
Starting the server executing from the root of the project: `docma serve ./docs`
![filestructure](https://user-images.githubusercontent.com/445985/48581902-f9b80700-e8d7-11e8-9903-58c1ad242d1e.jpg)

**Comment by onury** [comment]
@adampbragg Can you also provide your docma.json configuration?

**Comment by onury** [comment]
I tested your use case and actually it works for me bec. Docma CLI does all the arrangements required to run the app. It serves the `dest` and uses the `base` as the main route. When you run `docma serve`, see the initial logs for `Starting server @ ...` and `Serving SPA @ ...`.

Which Docma version are you using?

You could also simulate the remote structure within your `./docs` directory.
`./docs/your-lib/` as the `dest`, `/your-lib` as the `base`.

**Comment by adampbragg** [comment]
"docma": "^2.1.0"

Your "Side note" is what fixed this for me. Interestingly, not specifying the docs to serve like you mentioned generated the http://localhost:9000/my-library path.

@onury As my own side note, thank you for creating docma. It was the only documentation generation application that fit my needs and generated clear usable docs. And, thank you for your help in clearing this up for me.

**Comment by onury** [comment]
You're welcome. Good to hear your issue is resolved. 
I'll underline that side not in Docma's documentation.

**Comment by onury** [comment]
Note: I'm also adding a new option for Docma CLI to override/set the base path from command line.
```sh
docma serve -b /library    # sets the base path. alias: --base
```
