### ISSUE TITLE
Hierarchy/Outline displays incorrectly

### ISSUE THREAD

**Issue by dannyrb** [onury/docma#58]
## Problem

Code organized by `namespace` is not sorted or grouped correctly.

### Image Examples:

1. (Not working, oddly) Correct level of nesting, but not grouped under correct `namespace`:

![image](https://user-images.githubusercontent.com/5797588/48375632-8d9a9080-e696-11e8-9337-8d87c5bbec80.png)

2. (Working) Some tools are correctly grouped under the `namespace`:

![image](https://user-images.githubusercontent.com/5797588/48375684-a99e3200-e696-11e8-8946-1073774f905f.png)

### Code Snippet Examples:

**Grouped Correctly**
Example configuration for pictured `LengthTool`:
```js
/**
 * @public
 * @class LengthTool
 * @memberof Tools.Annotation
 *
 * @classdesc Tool for measuring distances.
 * @extends BaseAnnotationTool
 */
export default class LengthTool extends BaseAnnotationTool {
...
}
```

**Not Grouped Correctly**
Example configuration for pictured `AngleTool`:

```js
/**
 * @public
 * @class AngleTool
 * @memberof Tools.Annotation
 *
 * @classdesc Create and position an angle by placing three consecutive points.
 * @extends BaseAnnotationTool
 */
export default class AngleTool extends BaseAnnotationTool {
...
}
```

**Comment by onury** [comment]
This is typically a user / documenting issue. Just change your `debug` config to output jsdoc json files and inspect how they're parsed by JSDoc.

Generally this is solved with either `@memberof!` tag (notice the bang suffix) or instead of using `@memberof`, the best way to organize is to specify the full name via `@name` tag. Note that when you do, you'll also need to specify the type. i.e. `@function` if it's a method.

In your case, you may try 
```js
/**
 * @public
 * @name Tools.Annotation.AngleTool
 * @class
 *
 * @classdesc Create and position an angle by placing three consecutive points.
 * @extends BaseAnnotationTool
 */
export default class AngleTool extends BaseAnnotationTool {
    ...
}
```

**Comment by onury** [comment]
Another thought:
Do you somehow have `Tools.Annotation` definition and `LengthTool` in the same file and `AngleTool` in another? Bec. there has to be structural issue how you define the hierarchy of your symbols since LengthTool` and `AngleTool` definitions look very similar.

**Comment by dannyrb** [comment]
> Do you somehow have Tools.Annotation definition and LengthTool in the same file and AngleTool in another?

It makes sense you would think that. That's part of the reason I'm so perplexed. I create the namespace in the `index.js` for the directory that contains both tools. Both tools are imported into it, and then re-exported as `named exports`, and grouped as part of a larger `default export` that contains all annotation tools. As far as I can tell, there are no structural differences between the two.

```
 tools
    ├── ...
    ├── annotation/                  # All annotation tools live here
    │   ├── AngleTool.js             # Single file, default export
    │   ├── index.js                 # Exports, Named: each tool; Default: all tools
    │   └── LengthTool.js            # Single file, default export
    └── ...
```

Thanks for the note to check the raw logs, and on potential ways to fix the hierarchy with doc changes. I'll report back and close this issue when I've resolved 👍

**Comment by dannyrb** [comment]
I appreciate the notes about `src` configuration influencing route splitting and symbols 👍 However, I believe I am still confused. For my situation:

> If you're not grouping any JS files with a named route (e.g. src: ["src/*.js"]), all will be available under the default API route i.e. /?api.

My configuration is similar to this: `"src": ["./src/**/*.js", "./README.md"],`

> - The top-most symbol(s) have more than 1 level: `a.b` (second level) exists but a (first) does not,
> - or some symbol(s) do not have their parent level: `a` and `a.b.c` exists but a.b does not,
then you'll have a visual issue with tree outlining..

1. I declare my namespace in `index.js` as `@namespace Tools.Annotations`
2. **In the same directory**, in each file that has a single default export, I mark the tool class identically with:
  - `@memberof Tools.Annotations`
  - `@class MyToolName`

To clarify, all namespaces and classes are defined in this directory: 

![image](https://user-images.githubusercontent.com/5797588/48384541-e844e400-e6b8-11e8-97d5-dd8436d11ce4.png)

All tools listed below `index.js` in the same directory are correctly linked. All tools listed above `index.js` in the same directory are incorrectly linked,

> Editors you use will not have this issue bec. they have all the data they need. If you need a similar output, you should not name-group at all and provide all the doc data to the same page/route.

This makes sense, but I am not name-grouping by page/route. All documentation currently sits on the same page.

<hr />

At this point, you've provided me with enough information to debug and work around this problem. I appreciate all of the advice and guidance ^_^ My above comments are mostly to make sure I firmly grasp the issue.

**Comment by onury** [comment]
Can you provide a mock version of your structure? Only JSDoc comments with file/folder structure is enough. I'll take a look.

**Comment by dannyrb** [comment]
### Structure

```
 src/tools/
    ├── ...
    ├── annotation/                  # All annotation tools live here
    │   ├── AngleTool.js             # Single file, default export
    │   ├── index.js                 # Exports, Named: each tool; Default: all tools
    │   └── LengthTool.js            # Single file, default export
    └── ...
```

### JSDoc

### Code Snippet Examples:

`src/tools/annotation/index.js`
```js
/**
 * Tools that extend the {@link Tools.Base.BaseAnnotationTool|`BaseAnnotationTool`}
 * @namespace Tools.Annotation
 */
```

`src/tools/annotation/AngleTool.js`
```js
/**
 * @public
 * @class AngleTool
 * @memberof Tools.Annotation
 *
 * @classdesc Create and position an angle by placing three consecutive points.
 * @extends Tools.Base.BaseAnnotationTool
 */
export default class AngleTool extends BaseAnnotationTool {
...
}
```

`src/tools/annotation/LengthTool.js`
```js
/**
 * @public
 * @class LengthTool
 * @memberof Tools.Annotation
 *
 * @classdesc Tool for measuring distances.
 * @extends Tools.Base.BaseAnnotationTool
 */
export default class LengthTool extends BaseAnnotationTool {
...
}
```

### Docma Configuration

```json
{
  "src": ["./src/**/*.js", "./README.md"],
  "dest": "./docs/latest/api",
  "debug": 31,
  "app": {
    "title": "Cornerstone Tools: API Docs",
    "routing": "query",
    "base": "/",
    "server": "github"
  },
  "jsdoc": {
    "hierarchy": true,
    "package": true,
    "private": false,
    "undescribed": false
  },
  "template": {
    "path": "zebra",
    "options": {
      "navbar": true,
      "sidebar": {
        "enabled": true,
        "outline": "tree"
      }
    }
  }
}
```

**Comment by onury** [comment]
I created the exact test with your structure and config.

<img width="1040" alt="docma-test-1" src="https://user-images.githubusercontent.com/3665990/48524168-57c0fc00-e890-11e8-81da-6c715bbaa46e.png">

As you see, the outline is as expected. So I'm not really sure what's the problem..

There is no definition for `Tools`, so the very first node of the tree is also branched.
If you define `Tools` in one of the files, it will also have its own node.

This is done with Docma v2.1.0 (latest as of now).

Test project: [docma-test-1.zip](https://github.com/onury/docma/files/2583307/docma-test-1.zip)

**Comment by ahmadassaf** [comment]
@dannyrb I am wondering if you have resolved this as I am facing the same exact issue in #103
