### ISSUE TITLE
Add @default tag support

### ISSUE THREAD

**Issue by aaronmallen** [onury/docma#60]
given:

```javascript
/**
 * A base uri
 *
 * @constant
 * @default
 */
  const BASE_URI = 'http://my-example.com'
```

vanilla jsdoc would display the value of the constant here as I have labeled it as a default, I'd like to see the same support for the tag in docma.

**Comment by onury** [comment]
This was already supported for symbol parameters. 
Added support for symbol itself.
Available in [Docma 3.1.0](https://onury.io/docma/changelog#310--2018-12-04-).
