### ISSUE TITLE
After v2/v3 migration: @extends is empty

### ISSUE THREAD

**Issue by warpdesign** [onury/docma#71]
My partial looks like this:

```html
```

This is what my jsDocs look like:

```js
/**
 * The menu class allows to quickly add text menu to an Athena Scene
 *
 * Each menu entry is called menuItem and is a simple object with the following properties:
 * `{ text: 'menu text', selectable: true|false, active: true|false, visible: true|false }`
 *
 * @extends Drawable
 */
class Menu extends Drawable {
}
```

In v1 this worked as expected, displaying a link in the generated html page:

![image](https://user-images.githubusercontent.com/199648/53560802-861bcc00-3b4d-11e9-876d-292cf3e5f895.png)

But when built using docma v2/3, the link doesn't appear next to "extends":

![image](https://user-images.githubusercontent.com/199648/53560857-a2b80400-3b4d-11e9-9fbb-6f470858821c.png)

**Comment by warpdesign** [comment]
I also noticed that this particular doc section takes a very long time to be rendered: something like 3-4 seconds, in local.

This seems too long, even though the json that's loaded is rather big: ~400kb.

**Comment by onury** [comment]
In Docma v1.x there was no auto-link feature. it was first introduced with v2.0.0. Docma calculates the link and provides `$docmaLink` property but the actual HTML linking is done via the template, not by Docma. 

Could that be about your template? Maybe some part is not compatible with Docma web? Can you check the HTML source (by right clicking, then view source)?

**Comment by warpdesign** [comment]
Actually this was implemented inside the 1.x template, but it was using an API that has changed as well, so was returning an empty string.
