### ISSUE TITLE
@note

### ISSUE THREAD

**Issue by warpdesign** [onury/docma#73]
I have some notes in my code, in the form of:

```js
/**
  *
  * @note: some text here
**/
```

Docma simply adds a `note:` in the generated documentation, but without the text after so it's quite useless.

Reading the JSDoc documentation, I couldn't find  `@note` so it may not be officially supported.

Shouldn't Docma simply skip it if that's not the case? or print it as-is maybe?

**Comment by onury** [comment]
You probably have `jsdoc.allowUnknownTags` set to `true` (which is by default if you've omitted) in your [build configuration](https://onury.io/docma/api#Docma~BuildConfiguration). It will allow the tag but may/will not include the text (JSDoc core related).
