### ISSUE TITLE
Wrong paths in index.html

### ISSUE THREAD

**Issue by Woosy** [onury/docma#74]
Hi,
I just tried to use docma for the very first time, by using the following command `docma -s app:src/app.js  -d doc/`.

However when I opened the generated `index.html` file, I had a blank page.
When I opened Chrome's inspector, I saw that none of the file loaded (see following image)
![image](https://user-images.githubusercontent.com/26418696/54313378-8306ee00-45d9-11e9-835c-9db9206d6b7e.png)
All files failed with `ERR_FILE_NOT_FOUND`.

The generated `index.html` looked like this :
![image](https://user-images.githubusercontent.com/26418696/54313510-cfeac480-45d9-11e9-8731-cab01e5af186.png)

When I remove the `<base href="/">`, all js & css files loads, but jquery and fontawesome are failing (because they are missing `https:`)
And if I don't remove the base tag, I need to set all assets `src` to their absolute path on my disk (& still add the `https:` for jquery & fontawesome)

Seems like something's wrong

(using node 10.15.1 on Linux, & docma v3.2.2, zebra 2.3.1)

**Comment by onury** [comment]
You should run an http server to test/view the generated SPA. You can use the built-in `docma serve` command or any other static files server.

**Comment by Woosy** [comment]
After a lot of struggle, I finally managed to get it up and running via `docma serve`.
It wasn't that difficult, but I find that the explanations were pretty difficult to understand for a beginner..

**Comment by onury** [comment]
Is it the wording in the docs? A missing example?
Pls let me know which part was difficult to understand so we can make it easier.
