### ISSUE TITLE
left fly-out list has no scroll-bar in Firefox

### ISSUE THREAD

**Issue by dkebler** [onury/docma#8]
In tasktimer docma while viewing in the latest firefox (50.0.2 on linux) there is no scroll to get to the last items.  Works fine the chrome.

Also curious why addTask is considered public by jsdoc but it doesn't appear in built site?
Just never built?  or does docma allow exclusion of certain elements in the builder file?

Well, might as well start putting in my jsdoc stuff. I'll give a run later.

Tasktimer looks like a good example to refer to.. thx

**Comment by onury** [comment]
Thanks. Fixed the scroll issue for Firefox. Released v1.4.0 with some other fixes and tweaks. Pls update to the latest.

For TaskTimer documentation, I need to check that later. It's a different repo so closing this issue for Docma.
