### ISSUE TITLE
Strange parsing issue(?)

### ISSUE THREAD

**Issue by takase1121** [onury/docma#83]
I have this file structure.
![image](https://user-images.githubusercontent.com/20792268/61172877-a8266000-a5bd-11e9-8dbe-e8456ac89939.png)
However when I generate the docs the tree became like this instead
![image](https://user-images.githubusercontent.com/20792268/61172882-ba080300-a5bd-11e9-8f3e-b122e542f165.png)
(`.parse` is a static method in `DocLoader`)

**Comment by onury** [comment]
JSDoc does not care about the file structure. It's about class/namespace hierarchy.
Docma tree outline shows that the hierarchy is not correctly documented with JSDoc.

Make sure your `parse()` function is a child of `DocLoader`.
One way is this:
```js
/**
 *  Some description...
 *  @name DocLoader.parse
 *  @function
 */
parse() { 
 // ...
}
```
or you could use `@memberof`
..

Pls consult JSDoc documentation.

**Comment by takase1121** [comment]
none of your suggestion worked. Here is a snippet of code I had.
```js
export class DocLoader {
    /**
     * Parses a file
     * @param {string} filename The filename to parse
     */
    static async parse(filename) {
        ...
    }
}
```
I really can't find out where's the issue

**Comment by onury** [comment]
It seems you didn't document `DocLoader`.

**Comment by takase1121** [comment]
How do I do that?

**Comment by takase1121** [comment]
Thanks for your help. Apparently I just have to document the classes with `@class` tag  now it works fine.
