### ISSUE TITLE
option to put API docs for each file on a separate page?

### ISSUE THREAD

**Issue by trusktr** [onury/docma#85]
I have a bunch of classes in separate files, and I noticed that it places all the docs for all the classes on a single page. Can we control this, and put them on separate pages?

**Comment by trusktr** [comment]
Looks like I have to specify each page? f.e.:

```js
{
    "src": [
        {
            "Motor": "./src/core/Motor",
            "Node": "./src/core/Node",
            // etc...
        }
    ],
    "dest": "./docs"
}
```

Maybe I can just generate this file...

**Comment by trusktr** [comment]
It looks like the answer is to generate the `src` config so that my classes are on separate pages.

**Comment by trusktr** [comment]
After putting classes on separate pages, I realized that the sidebar can not link to all classes, only to the content of the current page (and same with search), so I made a new question about that: https://github.com/onury/docma/issues/86

**Comment by onury** [comment]
Sidebar is an outliner, not a navigation menu. 
It lists symbols of the API belonging to your current path.
Use the top nav bar for navigating different documentations.
