### ISSUE TITLE
Won't create

### ISSUE THREAD

**Issue by Bizarrus** [onury/docma#9]
I've tried to generate a Documentation.

Tested on my empty JS-Function:

    /**
    	@class GameSocket
    */
    var GameSocket = (new function GameSocket() {
	
    }());

But noting will generated. Can't find informations about the Comments-Syntax. On YUIDoc this will works, but i want to search alternatives.

**Comment by onury** [comment]
See [JSDoc documentation](http://usejsdoc.org).

**Comment by onury** [comment]
Your code has no documentation, so your JSDoc outputs an empty array. Add some description and try again. You can set debug option to `31` to enable logs and output generated jsdoc file.

Also a note, you shouldn't use `new` before `function`.

BTW, fixed some issues and released Docma v1.4.0 
Pls update and try with the new version.
